version: "3.9"
services:
    flask-server:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        environment:
            FLASK_ENV: development
    front-end:
        build:
            context: ./front-end-app
            dockerfile: Dockerfile
        ports:
            - "3000:3000"